document.addEventListener('DOMContentLoaded', function () {
    // Recupera gli elementi del testo dinamico
    var textContainer1 = document.getElementById('text-container-1');
    var textContainer2 = document.getElementById('text-container-2');
    var textContainer3 = document.getElementById('text-container-3');
    var textContainer4 = document.getElementById('text-container-4');
    var textContainer5 = document.getElementById('text-container-5');
    var textContainer6 = document.getElementById('text-container-6');

    // Controlla la grandezza dello schermo e imposta il testo di conseguenza
    function updateText() {
        var windowWidth = window.innerWidth;

        if (windowWidth < 480) {
            textContainer1.innerHTML = 'Il presente documento è una sintesi rispetto alcuni punti salienti dell\'Accordo sulla riorganizzazione del settore Infrastrutture RFI.<br>L\'<a href="2024.01.10_ACCORDO_Manutenzione_Infrastrutture.pdf">accordo sottoscritto il 10 gennaio 2024</a> è stato caratterizzato...';
            textContainer2.innerHTML = 'CSE/DL livello professionale A figura professionale Impiegato Direttivo che svolgono compiti:<br>- Fino a 20 mln per gli appalti civili ed interessanti l\'intero ciclo di vita dell\'appalto.<br>- Fino a...';
            textContainer3.innerHTML = 'Le operazioni di gestione materiali vengono accentrate nella struttura di Programmazione e Controllo delle Unità Territoriali, fatta eccezione per la gestione dei materiali correnti e di pronto intervento,...';
            textContainer4.innerHTML = '<i><u>1 Responsabile</u> RSO</i> livello professionale Q posizione retributiva Q1.<br><u><i>1 Specialista infrastrutture</i></u> figura professionale professional Q posizione retributiva Q2. In tutte le UM...';
            textContainer5.innerHTML = '<b><i><u>La composizione delle squadre di manutenzione</u></i></b><br>Qualitativa terrà conto da quanto previsto dalle procedure in materia di sicurezza (es. Mol, Mov, ecc..)<br>Quantitativa<br>1 CT coordinerà...';
            textContainer6.innerHTML = '<b><i><u>UM Cantieri Meccanizzati</u></i></b><br>1 Responsabile RSO livello professionale Q posizione retributiva Q1.<br>1 Specialista Diagnostica figura professionale professional Q posizione retributiva Q2....';
        
        } else {
            textContainer1.innerHTML = 'Il presente documento è una sintesi rispetto alcuni punti salienti dell\'Accordo sulla riorganizzazione del settore Infrastrutture RFI.<br>L\'<a href="2024.01.10_ACCORDO_Manutenzione_Infrastrutture.pdf">accordo sottoscritto il 10 gennaio 2024</a> è stato caratterizzato da un confronto complesso durato quasi tre anni, sospeso nel maggio 2023, per volontà della Filt Cgil che ha rivendicato con forza che la sicurezza non sia più un semplice obiettivo da raggiungere, ma una priorità assoluta. Per questo, è necessario investire in sicurezza e garantire ai lavoratori le condizioni necessarie per operare in sicurezza.<br>Concetti ribaditi nel Settembre 2023 dalla Filt Cgil, nel documento politico <a href="deve esserci un dopo Brandizzo.pdf">"DEVE ESSERCI UN DOPO BRANDIZZO PER TUTTI"</a>, in cui si è chiesto: un maggior investimento in sicurezza, sia in termini di risorse finanziarie che di formazione obbligatoria (teorica e pratica) dei lavoratori di RFI e degli appalti; una revisione dell\'organizzazione del lavoro, che concili l\'esigenza aziendale di presidio manutentivo con quella di stabilire un\'equa ripartizione della prestazione lavorativa tra i lavoratori garantendo maggiori spazi manutentivi.<br>Il documento della Filt Cgil rappresenta un punto di partenza importante per avviare un dibattito serio e costruttivo sul tema della sicurezza nel settore dei trasporti e siamo soddisfatti che nell\'accordo sono stati recepiti i primi elementi qualificanti, rivendicati dalla Filt Cgil, che riportano al centro della discussione della contrattazione territoriale temi quali:<br><b>Internalizzazione e formazione</b><br>Acquisizione di nuovi treni e mezzi d\'opera per la realizzazione di attività core in house.<br>Percorsi di apprendimento sul campo per la internalizzazione di attività che non necessitano di mezzi d\'opera (cambio filo e revisione TE, risanamento di piccoli tratti di binario, sostituzione di tratti di rotaia).<br>Incremento del numero degli istruttori esclusivamente dedicati al rolo di formatori nell\'ambito della Technical Academy.<br><b>Sicurezza</b><br>Un rafforzamento del ruolo di controllo e verifica nei cantieri di lavoro, anche nei confronti delle ditte appaltatrici.<br>Sede permanente di incontri sulle tematiche riconducibili alla formazione e alla sicurezza del lavoro. Incontri trimestrali a livello nazionale e di norma semestrali a livello territoriale.';
            textContainer2.innerHTML = 'CSE/DL livello professionale A figura professionale Impiegato Direttivo che svolgono compiti:<br>- Fino a 20 mln per gli appalti civili ed interessanti l\'intero ciclo di vita dell\'appalto.<br>- Fino a 12 mln per gli appalti tecnologici ed interessanti l\'intero ciclo di vita dell\'appalto.<br>-Progettazione con compiti di verifica di progetti realizzati da terzi.<br>CSE/DL livello professionale Q parametro retribuito Q2 figura professionale professional<br>- Valori economici superiori ai precedenti punti.<br>- Progettazione relativi a progetti internalizzati.<br><i>Reparto Ponti e verifica opere d\'arte di SO Ingegneria</i>, in possesso di abilitazione OC2, che svolgono compiti di verifica livello professionale Q parametro retribuito Q2 figura professionale professional<br>Nell\'ottica di rafforzare il ruolo di controllo e verifica del committente RFI, le parti a livello di unità produttiva negozieranno quanto previsto in materia di orario di lavoro per individuare articolazioni di orario interessanti prevalentemente le fasce orarie/giornaliere caratterizzate dai cantieri notturni.';
            textContainer3.innerHTML = 'Le operazioni di gestione materiali vengono accentrate nella struttura di Programmazione e Controllo delle Unità Territoriali, fatta eccezione per la gestione dei materiali correnti e di pronto intervento, la valutazione tecnica e compilazione del registro carico/scarico rifiuti del tolta d\'opera e dei rifiuti generici che restano in ambito UM.<br>In ogni Magazzino Materiale (vedi allegato 3) sono previsti almeno 2 <i>addetti</i> alla gestione materiali con profilo professionale specialista tecnico amministrativo livello professionale B.<br>Restano confermate le manifestazioni di interesse già emanate.<br><b>Gestione delle visite annuali alle opere d\'arte</b><br>Struttura UO Nucleo Opera d\'Arte (sedi vedi allegato 3)<br><u>1 Responsabile</u> Figura professionale RLO livello professionale Q, posizione retributiva Q2.<br>Minimo <u>2 addetti</u> figura professionale capo tecnico infrastrutture livello professionale B.<br>Le risorse interessate dovranno essere in possesso di abilitazione OC1.';
            textContainer4.innerHTML = '<i><u>1 Responsabile</u> RSO</i> livello professionale Q posizione retributiva Q1.<br><u><i>1 Specialista infrastrutture</i></u> figura professionale professional Q posizione retributiva Q2. In tutte le UM con estensione compresa tra 180 km e 300 km e UM con aventi giurisdizione su linee definite Nodo, è presente un secondo specialista infrastrutture professional Q posizione retributiva Q2. Nelle UM IS con nuclei SCC è presente uno Specialista SCC figura professionale professional Q posizione retributiva Q2.<br><u><i>2 addetti figura professionale</u></i> specialista tecnico amministrativo livello professionale B.<br>A livello di Unità Produttiva le parti avvieranno un confronto finalizzato alla rivisitazione dell\'ambito di giurisdizione di ciascuna UM, individuando una estenzione pari a 150 km di linea (ad eccezione di UM Nodo e AV/AC) e non superiore a 300 km di linea, fermo restando la sussistenza degli attuali impianti, prevedendo anche l\'istituzione di nuove UM ove tale giurisdizione superi i 300 km,';
            textContainer5.innerHTML = '<b><i><u>La composizione delle squadre di manutenzione</u></i></b><br>Qualitativa terrà conto da quanto previsto dalle procedure in materia di sicurezza (es. Mol, Mov, ecc..)<br>Quantitativa<br>1 CT coordinerà gli addetti TMI/OSMI certificandone le attività espletate.<br>1 CT e 1 TMI in caso di attività complesse.<br><b><i><u>Nucleo manutentivo</u></i></b><br>4 squadre di manutenzione di cui 4 CT e 1 TMI ogni 5 addetti.<br>Nei nuclei manutentivi IS TE LAV ricadenti nelle linee AV, Nodi e nei nuclei ritenuti strategici (vedi allegato 4), sarà prevista una 5 squadra per estendere l\'attività di manutenzione preventiva nella fascia oraria 06.00/09.00 e per assicurare una maggiore regolarità e puntualità dei servizi ferroviari. A livello territoriale si potranno individuare altre località che saranno oggetto di valutazione in sede di verifica tecnica nazionale.';
            textContainer6.innerHTML = '<b><i><u>UM Cantieri Meccanizzati</u></i></b><br>1 Responsabile RSO livello professionale Q posizione retributiva Q1.<br>1 Specialista Diagnostica figura professionale professional Q posizione retributiva Q2.<br>1 Specialista CMA figura professionale professional Q posizione retributiva Q2.<br>1 Specialista CMTE figura professionale professional Q posizione retributiva Q2 (dove presenti cantieri Meccanizzati Te).<br>2 addetti profilo professionale specialista tecnico amministrativo livello professionale B.<br>Fermo restando il numero dei nuclei individuati, vedi allegato 3, a livello territoriale sarà possibile determinare sedi alternative.<br><u><i><b>UM TELECOMUNICAZIONI (TLC)</b></i></u><br>1 Responsabile RSO livello professionale Q posizione retributiva Q1.<br>1 Specialista GSMR figura professionale professional Q posizione retributiva Q2.<br>1 Specialista IaP figura professionale professional Q posizione retributiva Q2.<br>1 Specialista cavi figura professionale professional Q posizione retributiva Q2<br>2 addetti profilo professionale specialista tecnico amministrativo livello professionale B<br>Fermo restando il numero dei nuclei individuati, vedi allegato 3, a livello territoriale sarà possibile determinare sedi alternative.<br><b><i><u>UNITÀ MANUTENTIVE SOTTOSTAZIONI ELETTRICHE LP</u></i></b><br>1 Responsabile RSO livello professionale Q posizione retributiva Q1.<br>1 Specialista infrastrutture figura professionale professional Q posizione retributiva Q2.<br>1 Specialista telecomando dote figura professionale professional Q posizione retributiva Q2.<br>1 ulteriore Specialista infrastrutture nelle linee AV figura professionale professional Q posizione retributiva Q2.<br>2 addetti profilo professionale specialista tecnico amministrativo livello professionale B.<br>Fermo restando il numero dei nuclei individuati, vedi allegato 3, a livello territoriale sarà possibile determinere sedi alternative.<br><b><u><i>GESTIONE ESERCIZIO</i></u></b><br>1 Responsabile RSO livello professionale Q posizione retributiva Q1.<br>1 Specialista analista esercizio territoriale figura professionale professional Q posizione retributiva Q2<br>1 Specialista gestione esercizio figura professionale professional Q posizione retributiva Q2.<br>2 addetti profilo professionale specialista tecnico amministrativo livello professionale B.<br> Fermo restando il numero dei nuclei individuati, vedi allegato 3, a livello territoriale sarà possibile determinare sedi alternative.';
        }
    }

    // Aggiorna il testo quando la finestra viene ridimensionata
    window.addEventListener('resize', updateText);

    // Chiamata iniziale per impostare il testo in base alla dimensione iniziale della finestra
    updateText();
});
